### ISSUE TITLE
How to run predictions?

### ISSUE THREAD

**Issue by surenreddy** [DongjunLee/transformer-tensorflow#4]
I am getting an error "iterator has not been initialized" while running with --mode=test option.
This project would be really useful if we can predict from it. Could you help fix this issue?

**Comment by DongjunLee** [comment]
I didn't implement a test mode.
[tf.contrib.learn.Experiment](https://www.tensorflow.org/api_docs/python/tf/contrib/learn/Experiment#test)'s test mode is ambiguous in documents.

So, i always used estimator's predict method.

If you want predict mode, I'll add the infer.py that can use with below commands.

```bash
python infer.py --src "{src_sentence}"
```

**Comment by surenreddy** [comment]
Yes, that would be really helpful. Thank you.

**Comment by DongjunLee** [comment]
Check my latest commit.  :)

I implement `predict.py`.    https://github.com/DongjunLee/transformer-tensorflow/commit/b6585fa7504f0f35327f2a3994dac7b06b6036f7

**Comment by surenreddy** [comment]
Hi Dongjun, 
"predict.py" works fine... Thank you.
